//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class puntoDeVentaDB_testEntities : DbContext
    {
        public puntoDeVentaDB_testEntities()
            : base("name=puntoDeVentaDB_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ordenProductos> ordenProductos { get; set; }
        public virtual DbSet<ordenPromocion> ordenPromocion { get; set; }
        public virtual DbSet<promocionesProductos> promocionesProductos { get; set; }
        public virtual DbSet<cargoLaboral> cargoLaboral { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<orden> orden { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<promocion> promocion { get; set; }
        public virtual DbSet<clientes> clientes { get; set; }
    }
}
