//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public string ciEmpleado { get; set; }
        public string nombreEmp { get; set; }
        public string apellidoPtEmp { get; set; }
        public string apellidoMtEmp { get; set; }
        public string sexo { get; set; }
        public string direccionEmp { get; set; }
        public string correoEmp { get; set; }
        public Nullable<int> codCargoFK { get; set; }
        public Nullable<bool> eliminar { get; set; }
    
        public virtual cargoLaboral cargoLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
