//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.usuario = new HashSet<usuario>();
        }
    
        public string ciEmpleado { get; set; }
        public string nombreEmp { get; set; }
        public string apellidoPtEmp { get; set; }
        public string apellidoMtEmp { get; set; }
        public string sexo { get; set; }
        public string direccionEmp { get; set; }
        public string correoEmp { get; set; }
        public Nullable<int> codCargoFK { get; set; }
        public Nullable<bool> eliminar { get; set; }
    
        public virtual cargoLaboral cargoLaboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<usuario> usuario { get; set; }
        public virtual empleado empleado1 { get; set; }
        public virtual empleado empleado2 { get; set; }
    }
}
