//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class factura
    {
        public int codFactura { get; set; }
        public Nullable<int> codOrdenFK { get; set; }
        public Nullable<decimal> totalFactura { get; set; }
        public Nullable<bool> eliminar { get; set; }
    
        public virtual orden orden { get; set; }
    }
}
