//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenProductos
    {
        public int idOrdenProductos { get; set; }
        public Nullable<int> codOrdenFK { get; set; }
        public Nullable<int> codProductoFK { get; set; }
        public Nullable<int> cantidad { get; set; }
    
        public virtual orden orden { get; set; }
        public virtual productos productos { get; set; }
    }
}
