//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;

    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.ordenProductos = new HashSet<ordenProductos>();
            this.promocionesProductos = new HashSet<promocionesProductos>();
        }
    
        public int codProducto { get; set; }
        public string idProducto { get; set; }
        public string nombreProd { get; set; }
        public string descripcionProd { get; set; }
        public Nullable<int> codCategoriaFK { get; set; }
        public Nullable<decimal> precioProd { get; set; }
        public Nullable<decimal> costoProd { get; set; }
        public Nullable<bool> disponibilidadProd { get; set; }
        public byte[] imagenProd { get; set; }
        public Nullable<bool> eliminar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenProductos> ordenProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocionesProductos> promocionesProductos { get; set; }
        public virtual categorias categorias { get; set; }

        public static implicit operator DbSet<object>(productos v)
        {
            throw new NotImplementedException();
        }
    }
}
