//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocionesProductos
    {
        public int idPromProd { get; set; }
        public Nullable<int> codPromocionFK { get; set; }
        public Nullable<int> codProductoFK { get; set; }
    
        public virtual promocion promocion { get; set; }
        public virtual productos productos { get; set; }
    }
}
