//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocionesProductos
    {
        public int idPromProd { get; set; }
        public Nullable<int> codPromocionFK { get; set; }
        public Nullable<int> codProductoFK { get; set; }
    
        public virtual promocion promocion { get; set; }
        public virtual productos productos { get; set; }
    }
}
