//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public promocion()
        {
            this.ordenPromocion = new HashSet<ordenPromocion>();
            this.promocionesProductos = new HashSet<promocionesProductos>();
        }
    
        public int codPromocion { get; set; }
        public string idPromocion { get; set; }
        public string nomProm { get; set; }
        public Nullable<bool> estadoProm { get; set; }
        public string detalleProm { get; set; }
        public Nullable<decimal> precioProm { get; set; }
        public byte[] imagenProm { get; set; }
        public Nullable<bool> eliminar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenPromocion> ordenPromocion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocionesProductos> promocionesProductos { get; set; }
    }
}
