//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productos()
        {
            this.ordenProductos = new HashSet<ordenProductos>();
            this.promocionesProductos = new HashSet<promocionesProductos>();
        }
    
        public int codProducto { get; set; }
        public string idProducto { get; set; }
        public string nombreProd { get; set; }
        public string descripcionProd { get; set; }
        public Nullable<int> codCategoriaFK { get; set; }
        public Nullable<decimal> precioProd { get; set; }
        public Nullable<decimal> costoProd { get; set; }
        public Nullable<bool> disponibilidadProd { get; set; }
        public byte[] imagenProd { get; set; }
        public Nullable<bool> eliminar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ordenProductos> ordenProductos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<promocionesProductos> promocionesProductos { get; set; }
        public virtual categorias categorias { get; set; }
    }
}
